coverage:
  range: 70..100
  round: down
  precision: 1
  status:
    project:
      default: off
      python-sdk:
        target: 80%
        threshold: 5%
        flags:
          - python
        paths:
          - sdks/python
    patch:
      default:
        target: auto
        threshold: 0%
flags:
  python:
    paths:
      - sdks/python
    carryforward: true

  # rust:
  #   paths:
  #     - cli
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
