[project]
authors = [{ name = "Nagato Yuzuru", email = "x4.nagato.yuzuru@gmail.com" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

keywords = [
  "rule-engine",
  "predicate-logic",
  "schema-driven",
  "configuration",
  "policy-engine",
]

dependencies = [
  "case-converter>=1.2.0",
  "pydantic>=2.12.5",
  "typing-extensions>=4.15.0",
]
description = "An embedded, composable schema-driven predicate logic engine."
dynamic = ["version"]
license-files = ["LICENSE"]
name = "predylogic"
readme = "README.md"
requires-python = ">=3.10,<4.0"

[project.urls]
Documentation = "https://Nagato-Yuzuru.github.io/predylogic/"
Homepage = "https://Nagato-Yuzuru.github.io/predylogic/"
Repository = "https://github.com/Nagato-Yuzuru/predylogic"

[dependency-groups]
dev = ["tox-uv>=1.29.0", "deptry>=0.24.0", "ty>=0.0.14", "ruff>=0.14.14"]
prof = ["memray>=1.19.1", "py-spy>=0.4.1"]
test = [
  "polyfactory>=3.2.0",
  "pytest>=9.0.2",
  "pytest-benchmark>=5.2.3",
  "pytest-codeblocks>=0.17.0",
  "pytest-codspeed>=4.2.0",
  "pytest-cov>=7.0.0",
  "tach>=0.33.1",
  "ty>=0.0.13",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[tool.hatch.build.targets.wheel]
artifacts = ["src/predylogic/_version.py"]
packages = ["src/predylogic"]

[tool.hatch.version]
source = "vcs"
tag-pattern = "^sdks/python/v(?P<version>\\d+\\.\\d+\\.\\d+.*)"

[tool.hatch.version.raw-options]
root = "../.."

[tool.hatch.build.hooks.vcs]
version-file = "src/predylogic/_version.py"

[tool.hatch.build.targets.sdist]
artifacts = ["src/predylogic/_version.py"]


[tool.pytest.ini_options]
addopts = "--strict-markers"
norecursedirs = ["benchmarks"]
testpaths = ["tests"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["src"]

[tool.tox]
env_list = ["3.10", "3.11", "3.12", "3.13", "3.14", "lint"]
requires = ["tox-uv>=1.29.0"]

[tool.tox.env_run_base]
commands = [
  [
    "pytest",
    "--doctest-modules",
    "tests",
    "--cov",
    "--cov-config=pyproject.toml",
    "--cov-report=xml",
  ],
  [
    "ty",
    "check",
  ],
]
dependency_groups = ["test"]
pass_env = ["PYTHON_VERSION"]

[tool.tox.env.lint]
commands = [
  [
    "ruff",
    "check",
    "src",
    "tests",
  ],
  [
    "ruff",
    "format",
    "--check",
    "src",
    "tests",
  ],
]
dependency_groups = ["dev"]
