exclude = ["**/*__pycache__", "**/*egg-info", "**/tests", "**/.venv"]
forbid_circular_dependencies = true
ignore_type_checking_imports = true
layers = ["rule_engine", "register", "predicate", "trace", "typedefs"]
source_roots = ["src"]

[[modules]]
layer = "rule_engine"
path = "predylogic.rule_engine"

[[modules]]
layer = "register"
path = "predylogic.register"

[[modules]]
layer = "predicate"
path = "predylogic.predicate"

[[modules]]
layer = "trace"
path = "predylogic.trace"

[[modules]]
layer = "typedefs"
path = "predylogic.typedefs"
